name: Build and Push GPU Docker Image

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'Dockerfile.gpu'
      - 'requirements.txt'
      - 'setup.py'
      - 'indextts/**'
      - '.github/workflows/docker-build-gpu.yml'
  release:
    types: [published]
  workflow_dispatch:

env:
  IMAGE_NAME: indextts-gpu

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        elif [[ $GITHUB_REF == refs/heads/main ]] || [[ $GITHUB_REF == refs/heads/master ]]; then
          VERSION=latest
        else
          VERSION=${GITHUB_REF#refs/heads/}
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building GPU version: $VERSION"

    - name: Build and push GPU image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.gpu
        push: true
        platforms: linux/amd64
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1